version: "3"

services:
  web:
    build: ./docker/web
    container_name: web
    environment:
      TZ: "Asia/Tokyo"
    ports:
      - 80:80
    volumes:
      #appフォルダの中身をと/php-boting-app/appにbindマウントしてpcでappのファイルの変更をコンテナに反映させる
      #appフォルダをwebサーバから見れるようにするための設定
      - ./app:/php-voting-app/app
    depends_on:
      - db

  # dbサーバーを起動するための設定
  db:
    build: ./docker/db #dockerフォルダのdbファイルのdockerfileを参照する
    platform: linux/x86_64
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: password #mysqlのパスワード
      MYSQL_DATABASE: votingapp
      TZ: "Asia/Tokyo"
    ports:
      - 3307:3306
    volumes:
      - app_data:/var/lib/mysql #mysqlのデータを保存するための領域
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf #mysqlの設定の定義
    restart: always

#mysqlのデータを保存するためのストレージの作成
#コンテナとdocker上に作ったフォルダをvolumeマウントするためdocker上にフォルダを作成
volumes:
  app_data:
    driver: local
