version: "3"

services:
  # webサーバーを起動するための設定
  web:
    build: ./docker/web #dockerフォルダのwebファイルのdockerfileを参照する
    container_name: web #コンテナの名前
    environment: #サーバーの環境設定
      TZ: "Asia/Tokyo" #時刻を日本の時間に合わせる
    ports: #ブラウザでこのwebサーバーを見れるための参照
      - 80:80
    volumes:
      #appフォルダの中身をと/php-boting-app/appにbindマウントしてpcでappのファイルの変更をコンテナに反映させる
      #appフォルダをwebサーバから見れるようにするための設定
      - ./app:/php-voting-app/app
      - "./docker/web/httpd.conf:/etc/httpd/conf/httpd.conf"
    depends_on:
      - db

  # dbサーバーを起動するための設定
  db:
    build: ./docker/db #dockerフォルダのdbファイルのdockerfileを参照する
    platform: linux/x86_64
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: password #mysqlのパスワード
      MYSQL_DATABASE: votingapp
      TZ: "Asia/Tokyo"
    ports:
      - 3306:3306
    volumes:
      - app_data:/var/lib/mysql #mysqlのデータを保存するための領域
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf #mysqlの設定の定義
    restart: always

#mysqlのデータを保存するためのストレージの作成
#コンテナとdocker上に作ったフォルダをvolumeマウントするためdocker上にフォルダを作成
volumes:
  app_data:
    driver: local
